In [20]:
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix,  accuracy_score

In [21]:
df = pd.read_csv("emails.csv")

In [22]:
df.head()

,Email No.,the,to,ect,and,for,of,a,you,hou,...,connevey,jay,valued,lay,infrastructure,military,allowing,ff,dry,Prediction
0,Email 1,0,0,1,0,0,0,2,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Email 2,8,13,24,6,6,2,102,1,27,...,0,0,0,0,0,0,0,1,0,0
2,Email 3,0,0,1,0,0,0,8,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Email 4,0,5,22,0,5,1,51,2,10,...,0,0,0,0,0,0,0,0,0,0
4,Email 5,7,6,17,1,5,2,57,0,9,...,0,0,0,0,0,0,0,1,0,0

In [23]:
df.isnull().sum()

Email No.     0
the           0
to            0
ect           0
and           0
             ..
military      0
allowing      0
ff            0
dry           0
Prediction    0
Length: 3002, dtype: int64

In [24]:
X=df.drop(['Email No.','Prediction'],axis=1)
X

,the,to,ect,and,for,of,a,you,hou,in,...,enhancements,connevey,jay,valued,lay,infrastructure,military,allowing,ff,dry
0,0,0,1,0,0,0,2,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,8,13,24,6,6,2,102,1,27,18,...,0,0,0,0,0,0,0,0,1,0
2,0,0,1,0,0,0,8,0,0,4,...,0,0,0,0,0,0,0,0,0,0
3,0,5,22,0,5,1,51,2,10,1,...,0,0,0,0,0,0,0,0,0,0
4,7,6,17,1,5,2,57,0,9,3,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5167,2,2,2,3,0,0,32,0,0,5,...,0,0,0,0,0,0,0,0,0,0
5168,35,27,11,2,6,5,151,4,3,23,...,0,0,0,0,0,0,0,0,1,0
5169,0,0,1,1,0,0,11,0,0,1,...,0,0,0,0,0,0,0,0,0,0
5170,2,7,1,0,2,1,28,2,0,8,...,0,0,0,0,0,0,0,0,1,0
5171,22,24,5,1,6,5,148,8,2,23,...,0,0,0,0,0,0,0,0,0,0

In [25]:
Y=df['Prediction']
Y

0       0
1       0
2       0
3       0
4       0
       ..
5167    0
5168    0
5169    1
5170    1
5171    0
Name: Prediction, Length: 5172, dtype: int64

In [26]:
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size = 0.25)

In [27]:
#USING SVM
svm = SVC(kernel='linear', probability=True)
svm.fit(x_train, y_train)
y_pred_svm = svm.predict(x_test)
print("Accuracy Score for SVC : ", accuracy_score(y_pred_svm,y_test))

Accuracy Score for SVC :  0.9559164733178654

In [28]:
print("SVM Classification Report:")
print(classification_report(y_test, y_pred_svm))

SVM Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.96      0.97       935
           1       0.91      0.94      0.92       358

    accuracy                           0.96      1293
   macro avg       0.94      0.95      0.95      1293
weighted avg       0.96      0.96      0.96      1293

In [29]:
print("SVM Confusion Matrix:\n", confusion_matrix(y_test, y_pred_svm))

SVM Confusion Matrix:
 [[900  35]
 [ 22 336]]

In [30]:
#USING KNN
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train, y_train)
y_pred_knn = knn.predict(x_test)
print(y_pred_knn)

[0 1 0 ... 0 0 0]

In [31]:
print(knn.score(x_test, y_test))

0.8638824439288476

In [32]:
print("KNN Classification Report:")
print(classification_report(y_test, y_pred_knn))

KNN Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.87      0.90       935
           1       0.72      0.84      0.77       358

    accuracy                           0.86      1293
   macro avg       0.83      0.86      0.84      1293
weighted avg       0.87      0.86      0.87      1293

In [33]:
print("KNN Confusion Matrix:\n", confusion_matrix(y_test, y_pred_knn))

KNN Confusion Matrix:
 [[816 119]
 [ 57 301]]